image: docker/compose:alpine-1.28.0

stages:
  - build
  - lint
  - test
  - deploy

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - apk add make
  - cat $BACKEND_DOT_ENV > $(pwd)/backend/src/config/.env
  - cat $CERTBOT_DOT_ENV > $(pwd)/.env
  - cat $FRONTEND_DOT_ENV > $(pwd)/frontend/.env

build:
  stage: build
  tags:
    - build
  script: make build push
  only:
    - master

lint:
  stage: lint
  tags:
    - lint
  script: make pull lint

test:
  stage: test
  tags:
    - test
  script: make pull test
  only:
    - master

deploy:
  stage: deploy
  tags:
    - deploy
  script: make restart
  only:
    - master