version: "3.3"

services:
  nginx:
    build: ./
    container_name: nginx
    restart: always
    volumes:
      - ssl_secrets:/etc/letsencrypt
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app

  app:
    build: backend/
    container_name: app
    command: make migrate run
    restart: always
    env_file:
      - backend/src/config/.env
    volumes:
      - ./logs:/app/logs
    environment:
      POSTGRES_HOST: postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:14-alpine
    container_name: postgres
    restart: always
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
    env_file:
      - backend/src/config/.env
    volumes:
      - ./pgdata:/var/lib/postgresql/data

volumes:
  ssl_secrets: