version: "3.3"

services:
  api:
    build: .
    container_name: api
    command: make migrate run
    restart: always
    env_file:
      - src/config/.env
    environment:
      POSTGRES_HOST: db
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    container_name: db
    restart: always
    env_file:
      - src/config/.env
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: