# Generated by Django 4.0.6 on 2022-07-12 12:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Competition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("started_at", models.DateTimeField()),
                ("registration_before", models.DateTimeField()),
                ("type", models.IntegerField(choices=[(0, "Personal"), (1, "Team")])),
                ("person_amount", models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                "verbose_name": "Competition",
                "verbose_name_plural": "Competitions",
                "db_table": "competitions",
            },
        ),
        migrations.CreateModel(
            name="Field",
            fields=[
                ("id", models.CharField(max_length=127, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=127)),
                (
                    "type",
                    models.IntegerField(choices=[(0, "Text"), (1, "List"), (2, "Checkbox"), (3, "Date"), (4, "File")]),
                ),
            ],
            options={
                "verbose_name": "Field",
                "verbose_name_plural": "Fields",
                "db_table": "fields",
            },
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ],
            options={
                "verbose_name": "Participant",
                "verbose_name_plural": "Participants",
                "db_table": "participants",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=127)),
                ("surname", models.CharField(max_length=127)),
                ("patronymic", models.CharField(max_length=127, null=True)),
                (
                    "permission",
                    models.IntegerField(
                        choices=[(0, "Default"), (1, "Teacher"), (2, "Admin"), (3, "Super Admin")], default=0
                    ),
                ),
                ("email", models.EmailField(max_length=254, null=True, unique=True)),
                ("phone", models.CharField(max_length=15, null=True)),
                ("region", models.CharField(max_length=255, null=True)),
                ("school", models.CharField(max_length=255, null=True)),
                ("school_class", models.CharField(max_length=15, null=True)),
                ("vkontakte_id", models.CharField(max_length=255, null=True, unique=True)),
                ("google_id", models.CharField(max_length=255, null=True, unique=True)),
                ("telegram_id", models.CharField(max_length=255, null=True, unique=True)),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="Request",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("team_name", models.CharField(max_length=255)),
                ("status", models.IntegerField(choices=[(0, "Awaited"), (1, "Accepted"), (2, "Rejected")], default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="requests", to="api.competition"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="created_requests", to="api.user"
                    ),
                ),
                ("participants", models.ManyToManyField(through="api.Participant", to="api.user")),
            ],
            options={
                "verbose_name": "Request",
                "verbose_name_plural": "Requests",
                "db_table": "requests",
            },
        ),
        migrations.CreateModel(
            name="RefreshToken",
            fields=[
                ("value", models.CharField(max_length=255, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("revoked", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="refresh_tokens", to="api.user"
                    ),
                ),
            ],
            options={
                "verbose_name": "Refresh Token",
                "verbose_name_plural": "Refresh Tokens",
                "db_table": "refresh_tokens",
            },
        ),
        migrations.AddField(
            model_name="participant",
            name="request",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.request"),
        ),
        migrations.AddField(
            model_name="participant",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.user"),
        ),
        migrations.CreateModel(
            name="DefaultValue",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value", models.CharField(max_length=255)),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="default_values", to="api.field"
                    ),
                ),
            ],
            options={
                "db_table": "default_values",
            },
        ),
        migrations.CreateModel(
            name="CompetitionField",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_required", models.BooleanField(default=True)),
                ("is_visible", models.BooleanField(default=True)),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="fields", to="api.competition"
                    ),
                ),
                ("field", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.field")),
            ],
            options={
                "db_table": "competitions_fields",
            },
        ),
        migrations.CreateModel(
            name="RequestValue",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value", models.CharField(max_length=511)),
                (
                    "form_field",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.competitionfield"),
                ),
                ("participant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.participant")),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="form_values", to="api.request"
                    ),
                ),
            ],
            options={
                "db_table": "requests_values",
                "unique_together": {("participant", "form_field")},
            },
        ),
    ]
