# Generated by Django 4.0.6 on 2022-07-27 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_add_admins_and_request_template_fields_and_rename_peron_amount_in__competitions"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="participation",
            unique_together={("request", "user")},
        ),
    ]
