# Generated by Django 4.0.6 on 2022-07-30 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_add_unique_constraint_in_participants"),
    ]

    operations = [
        migrations.AlterField(
            model_name="field",
            name="type",
            field=models.IntegerField(),
        ),
    ]
