# Generated by Django 4.0.7 on 2022-08-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_type_field_in_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="surname",
            field=models.CharField(max_length=127, null=True),
        ),
    ]
