# Generated by Django 4.0.7 on 2022-08-05 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_users_and_competition_tables"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participation",
            name="request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="participation", to="api.request"
            ),
        ),
    ]
