# Generated by Django 4.0.7 on 2022-08-08 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_alter_request_field_in_participations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="status",
            field=models.CharField(
                choices=[
                    ("awaited", "Awaited"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("canceled", "Canceled"),
                ],
                default="awaited",
                max_length=31,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="institution_type",
            field=models.CharField(
                choices=[("school", "School"), ("college", "College"), ("university", "University")],
                max_length=31,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="permission",
            field=models.CharField(
                choices=[
                    ("default", "Default"),
                    ("teacher", "Teacher"),
                    ("admin", "Admin"),
                    ("super_admin", "Super Admin"),
                ],
                default="default",
                max_length=31,
            ),
        ),
    ]
