# Generated by Django 4.0.7 on 2022-08-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_alter_choice_values"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competition",
            name="fields",
            field=models.ManyToManyField(related_name="competitions", to="api.field"),
        ),
    ]
